---
version: "2.0"

services:
  db:
    image: postgres:latest
    expose:
      - port: 5432
        proto: tcp
        to:
          - service: odoo
    env:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      
  odoo:
    image: odoo:latest
    depends_on:
      - db
    expose:
      - port: 8069
        to:
          - global: true
    # tty: true
    env:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

profiles:
  compute:
    db:
      resources:
        cpu:
          units: 1 
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    odoo:
      resources:
        cpu:
          units: 1 
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    westcoast:
      attributes:
        host: akash
<<<<<<< HEAD
=======
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
>>>>>>> 84e21dbe0c75ddd20ac6144b3b7fabba2c9b7ce5
      pricing:
        db: 
          denom: uakt
          amount: 100
        odoo: 
          denom: uakt
          amount: 100

deployment:
  db:
    westcoast:
      profile: db
      count: 1 
  odoo:
    westcoast:
      profile: odoo
      count: 1 
